# Paths are relative to the directory containing the configuration file.
filesystem:
  base_path: "./example/"
metadata:
  base_path: "./metadata/"
session:
  database: "rime_session.db"
media_url_prefix: "http://localhost:3000/media/"
plugins:
  anonymise:
    # - "ml_names"
